stages: 
 - build
 - deploy

cache:
   paths:
   - target


variables:
 MAVEN_OPTS: "-Dmaven.repo.local=/m2 -Dmaven.test.skip=true"

build:
 stage: build 
 script:
   - mvn $MAVEN_OPTS clean install

local_deploy:
 stage: deploy
 before_script:
   - microdnf install which
   - 'which ssh-agent || ( microdnf install openssh-clients )'
   - eval $(ssh-agent -s)
   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh
   - ssh-keyscan 192.168.170.2 >> ~/.ssh/known_hosts
   - chmod 644 ~/.ssh/known_hosts
   - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
 script:
   - mv target/*.jar target/authentication.jar
   - ssh root@192.168.170.2 "systemctl stop authentication.service"
   - scp -r target/*.jar root@192.168.170.2:/usr/orangeline/ && ssh root@192.168.170.2 "systemctl start authentication.service"	
 only:
   - master
# when: manual

ibar_deploy:
 stage: deploy
 before_script:
   - microdnf install which
   - 'which ssh-agent || ( microdnf install openssh-clients )'
   - eval $(ssh-agent -s)
   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh
   - ssh-keyscan 172.31.64.49 >> ~/.ssh/known_hosts
   - chmod 644 ~/.ssh/known_hosts
   - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
 script:
   - ls -l target/
   - ssh support@172.31.64.49 "sudo systemctl stop authentication.service"
   - scp -r target/*.jar support@172.31.64.49:/usr/orangeline/ && ssh support@172.31.64.49 "sudo systemctl start authentication.service"	
 only:
   - master
 when: manual
