cloud:
  aws:
    credentials:
      access-key: AKIAXEDAIJD3QPNST3PD
      secret-key: 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
    region:
      static: eu-west-1
    stack:
      auto: false

application:
  bucket:
    name: enjooystorage

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB